# Generated by Django 5.2 on 2025-04-07 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_sets', models.PositiveIntegerField(default=0)),
                ('total_pieces', models.PositiveIntegerField(default=0)),
                ('App_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Set_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(default='', max_length=100, unique=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_group', to='collection_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Single_Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('theme_id', models.PositiveIntegerField(blank=True, null=True)),
                ('num_parts', models.PositiveIntegerField(blank=True, null=True)),
                ('set_img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('set_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_set', to='collection_app.set_group')),
            ],
        ),
    ]
