# Generated by Django 5.2 on 2025-04-08 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0002_single_set_difficulty_url_alter_set_group_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_group',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_group', to='collection_app.collection'),
        ),
    ]
