# Generated by Django 5.2 on 2025-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0004_alter_set_group_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_set',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
