# Generated by Django 5.2 on 2025-04-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0007_alter_collection_app_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='App_user',
            new_name='App_user_temp',
        ),
    ]
