# Generated by Django 5.2 on 2025-04-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0008_rename_app_user_collection_app_user_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='App_user_temp',
            new_name='App_user',
        ),
    ]
