# Generated by Django 5.2 on 2025-04-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0010_alter_set_group_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_group',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_group', to='collection_app.collection'),
        ),
        migrations.AlterField(
            model_name='single_set',
            name='set_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_set', to='collection_app.set_group'),
        ),
    ]
