# Generated by Django 5.2 on 2025-04-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0013_single_set_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_set',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
