# Generated by Django 5.2 on 2025-04-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0014_alter_single_set_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='set_group',
            constraint=models.UniqueConstraint(fields=('collection', 'set_name'), name='unique_group_per_collection'),
        ),
    ]
