# Generated by Django 5.2 on 2025-04-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0015_set_group_unique_group_per_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_group',
            name='set_name',
            field=models.CharField(max_length=100),
        ),
    ]
