# Generated by Django 5.2 on 2025-04-22 15:11

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0016_alter_set_group_set_name'),
    ]

    operations = [
        migrations.AlterField(
    model_name='single_set',
    name='theme_id',
    field=models.CharField(blank=True, null=True),
),
    ]
