# Generated by Django 5.2 on 2025-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0017_auto_20250422_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_set',
            name='set_num',
            field=models.CharField(blank=True, null=True),
        ),
    ]
