# Generated by Django 5.2 on 2025-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0018_single_set_set_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_set',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
