# Generated by Django 5.2 on 2025-04-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20250410_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile_images'),
        ),
    ]
