# Generated by Django 5.2 on 2025-04-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_app_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
